---
# Example:
# export_vars:
#   - { name: CACHE_DIR, value: /tmp/cache }
#   - { name: USER, value: bob }
- name: export vars
  lineinfile: >
    dest=/etc/environment
    line='export {{ item.name }}="{{ item.value }}"'
  with_items: export_vars
  sudo: yes
