---
- name: install Ubuntu
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - nodejs
  sudo: yes
  when: "ansible_distribution == 'Ubuntu'"

- name: install Debian
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - nodejs
    - nodejs-legacy
  sudo: yes
  when: "ansible_os_family == 'Debian' and ansible_distribution != 'Ubuntu'"

- name: npm install
  shell: >
    curl -sSL https://www.npmjs.org/install.sh | clean=no sh
    creates=/usr/bin/npm
  sudo: yes
